[package]
name = "sqlite"
description = "SQL common interface implementation for SQLite3"

authors.workspace = true
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true

[features]
macro = ["sql/macro"]

[dependencies]
sql.workspace = true

sqlite3.git = "https://github.com/shipsimfan/lib-sqlite3"
